# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-22 12:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='jobdescription',
            field=models.TextField(default=datetime.datetime(2016, 9, 22, 12, 22, 3, 781920, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
